env: "dev"

# Global defaults - applies to all chains unless overridden
defaults:
  from_latest: true
  poll_interval: "5s"
  reorg_rollback_window: 20
  client:
    timeout: "20s"
    max_retries: 3
    retry_delay: "5s"
  throttle:
    rps: 8
    burst: 16
    batch_size: 100
    concurrency: 3

chains:
  tron_mainnet:
    type: "tron"
    start_block: 75144237
    poll_interval: "8s"
    nodes:
      - url: "https://api.trongrid.io"
        auth:
          type: "header"
          key: "TRON-PRO-API-KEY"
          value: "a8ae1eff-23e5-4c63-912d-9136b1a442ce"
      - url: "https://tron-rpc.publicnode.com"
    client:
      max_retries: 5
      retry_delay: "10s"
    throttle:
      rps: 5
      burst: 8

  ethereum_mainnet:
    type: "evm"
    start_block: 23080871
    poll_interval: "3s"
    client:
      timeout: "30s"
    throttle:
      batch_size: 20
    nodes:
      - url: "https://ethereum-rpc.publicnode.com"
      - url: "https://eth.rpc.blxrbdn.com"
      - url: "https://eth.llamarpc.com"
      - url: "https://rpc.mevblocker.io"
      # - url: "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

  bnb_mainnet:
    internal_code: "BNB_MAINNET"
    type: "evm"
    start_block: 59040717
    reorg_rollback_window: 30
    nodes:
      - url: "https://bsc-rpc.publicnode.com"
      - url: "https://bsc.blockrazor.xyz"
      - url: "https://bnb.rpc.subquery.network/public"

# Infrastructure services
services:
  worker:
    manual:
      enabled: false
    catchup:
      enabled: false
    rescanner:
      enabled: true
    regular:
      enabled: true

  nats:
    url: "nats://localhost:4222"
    subject_prefix: "indexer.transaction"

  database:
    url: "postgres://postgres:postgres@localhost:5432/postgres"

  redis:
    url: "localhost:6379"
    password: ""

  kvstore:
    type: "consul"
    consul:
      scheme: "http"
      address: "127.0.0.1:8500"
      folder: "indexer"
      token: ""
      # http_auth:  # uncomment if needed
      #   username: ""
      #   password: ""

  bloomfilter:
    type: "redis"
    wallet_address_repo: "wallet_address"
    batch_size: 1000
    redis:
      key_prefix: "bloomfilter"
      error_rate: 0.01
      capacity: 1000000
    in_memory:  # alternative config
      expected_items: 1000000
      false_positive_rate: 0.01