chains:
  defaults:
    batch_size: 10
    poll_interval: "5s"
    client:
      timeout: "15s"
      max_retries: 3
      retry_delay: "5s"
      throttle:
        rps: 8
        burst: 16

  tron:
    name: "tron-mainnet"
    nodes:
      # Primary: TronGrid with API key (15 QPS limit)
      - url: "https://api.trongrid.io"
        headers:
          TRON-PRO-API-KEY: "${TRONGRID_TOKEN}"
        api_key_env: "TRONGRID_TOKEN"
      # Fallback: Public nodes (lower rate limits, no key needed)
      - url: "https://tron-rpc.publicnode.com"
      - url: "https://tron.drpc.org"
    start_block: 74399849
    from_latest: false
    poll_interval: "4s"  # Slightly slower to respect rate limits
    client:
      timeout: "15s"     # Longer timeout for potential rate limiting delays
      max_retries: 5     # More retries for 429/403 handling
      retry_delay: "10s" # Longer delay between retries for 403 blocks
      throttle:
        rps: 12          # Conservative: below 15 QPS limit
        burst: 15        # Small burst allowance

  evm:
    name: "ethereum-mainnet"
    nodes:
      - url: "https://ethereum-rpc.publicnode.com"
      - url: "https://1rpc.io/eth"
      # - url: "https://eth-mainnet.g.alchemy.com/v2/${API_KEY}"
        # api_key_env: "ALCHEMY_KEY"
      # - url: "wss://mainnet.infura.io/ws/v3/${API_KEY}"
        # api_key_env: "INFURA_KEY"
    start_block: 23080871
    from_latest: false
    client:
      timeout: "30s"
      throttle:
        rps: 5
        burst: 10

nats:
  url: "nats://localhost:4222"
  subject_prefix: "indexer.transaction"

storage:
  type: "memory"           # memory | badger | postgres
  directory: "data/badger" # only used for badger
